name: Update Latest Blog Posts

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest blog posts and badge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch

      - name: Run blog updater script
        run: node .github/scripts/update-mindware.js

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md mindware-badge.svg
          git commit -m "📝 Auto-update: latest blog posts + badge"
          git push
